name: Deploy to staging server
on:
    push:
        branches:
            - "main"

jobs:
    redeploy_frontend:
        runs-on: ubuntu-latest
        name: Deploy frontend to staging
        steps:
        - run: |
            echo ${{ secrets.sanket_AWS_key }}

