name: Deploy to staging server
on:
    push:
        branches:
            - "main"

jobs:
    deploy:
        name: Push to EC2
        runs-on: ubuntu-latest
        

        steps:
          - name: Checkout repo
            uses: actions/checkout@v4

          - name: Connect & Pull on EC2
            uses: appleboy/ssh-action@v1.0.3
            with:
                host: 65.2.175.106
                username: ubuntu
                key: ${{ secrets.SANKET_AWS_KEY }}
                script: |
                    cd monorepo-cicd
                    git pull origin main
                    pnpm install
                    cd packages/db
                    pnpx prisma generate
                    cd ../..
                    pnpm run build
                    pnpm run start




        
           

